apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    # Let's Encrypt 프로덕션 서버 URL
    server: https://acme-v02.api.letsencrypt.org/directory
    email: kdh@didim365.com
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - http01:
        ingress:
          class: nginx
